### ISSUE TITLE
Is the project still in progress?

### ISSUE THREAD

**Issue by mhsfh** [Coordinate-Cat/castra#7]
hello, i hope you are doing well
i just saw your repo and i liked the idea of the app and the technologies you are using,and i would like to contribute in this project if there are design and you are plannig to keep going with this project
thanks

**Comment by Coordinate-Cat** [comment]
hi!
I'm trying to put the most effort into this project right now.
If you have any bugs or fixes, please feel free to submit an issue or PR!

**Comment by mhsfh** [comment]
thanks for the welcoming, 
can you send me the design and create issues boards so i can pick ones and work on em to avoid working on the same task,

**Comment by Coordinate-Cat** [comment]
HNY @mhsfh 
Sorry, my understanding of English is so poor that I missed your question.

Currently, there are no design specifications for this project. So there is nothing I can help you with around design yet...
As we add more pages, we may need bug fixes or other input. If you still have the volunteer spirit at that time, we would appreciate your efforts:)
